### ISSUE TITLE
Trade for these items market fetch isn't working

### ISSUE THREAD

**Issue by CashKiller28** [PathOfBuildingCommunity/PathOfBuilding-PoE2#251]
### Check version

- [x] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Checked for updates and i'm in the latest version. No warning errors appearing. Fetch items correctly.

### How does Path of Building behave?

Checked for updates and i'm in the latest version. No warning errors appearing. When i try to search for any item, it returns this error bellow:

![Image](https://github.com/user-attachments/assets/6f2a8a88-38b0-4d6c-a2e9-70fd6e290b86)

### How to reproduce the issue

Look for any item on the "Trade for these items" menu.

### Character build code

```shell
eNrtPWtz2ziSn0e_gqWqvboryzbfpHL2XMmWXxk7cSw7nuyXFC1CFhOKVPiwrWztf79uABRBmqQo-XZLu5et2owMdDeARqNfePDgf15mvvREotgLg8Ousid3JRKMQ9cLHg-7d7enu3b3f37vHFw7yfTj5Cj1fKxRf-_8dkD_kHzyRPzDbl_rSmPfieMPzowcdm-c4JFEXcmJxyRwj_OKIXFcsiBdKXGiR5J8zhqWvypAYOpEzjgh0SUSHaRJeBW6gJREKWDMHC8YhePvJDmLwnQOne1KTx55ZjAXV9cfb2670LHfDq59Z0GiUeIkUgz_HHYHMEDnkZx7CaA4fgrwuiHLe7Ymayr8X9O7-42YR2kUJ0NnBj_XpTCaE-IukZQ9266DvI7IyWRCxon3RI4jLzmeOsE4b0-uw1sX9ir1E2_uezhBHF7dU6w6lPNX1BW5lv5tmDj-8Hq0hLV1U9kzTECxNFm1mvHCZPUI7r1keuQDTzdoBXEvHgMvIRsiX4deHAZvGJ-IWj9Jqe_DKmsFe0NiEj05iVfsVj3tcPbgBRtx78oJnOMwbjFHCHlNIlj7yVoIIzIOQV2s28aamJfehLSHXGscHGHd3mw2jpNRW7i1CW_WoRtQj-0gR2Hqt4RMci1lq3VQQ_KS6zK1YbH8KEAqtQQvgrxvqtFEUIRU-kp9D59CXKSrR0xVxcn5dU5VtxR5ry_LpmbKar35mC5ib-z4V86LN0tnoLZvne8kb1A3jX69ED5OkwB0Th2yYvV1rQ771IvIRojHoe9uhjh1wrgO09TVftNqy5sw60UFzPb4HUJfBONcAJvI3gUR1cWitW9oAFFuYHGhg_Hgk9Y4eTN8kbYxy6yxRxLwFhft9NIlIePpGfhdN05C2qnkvDdK_SxQ5iK0yNxGslXMbWigiLIGoxCxmlGGstfY3Jq8Gs29SHBHFUNrhqxgQGuMV-Pf65uyZeuaolmqYdSagYBEj4vR1CO-wHWjXjxFhIx_x868FS4VCZGAKBq63a7JtQRcRF1z8u6dyG1nDtft05MTi0ZCN-stCuMYQxCZ1SBKVwQcZ0BxScmjN6z6oCT8hiGJvybeIJqFadRmHcAoGHArZZBZORaM3RA3Hbczq8vQ6siHILJtvLTEgn76_lqogyRxxt-HoftI2qLQRtbCKPZvlM7nsOhRItoSQNsNMYQn-GKWsRr4I8izuLStJhPfmn4OXKavrfRcWjdSwii3JDf6HKVWTL0FdOsWlpN5BepiBhqb5g6uQjF9YMi1TZ5C2NgqBqSALWPR6_AZej_FbE28HjS4Z6un7zQiwc9Fa_oF8FYNnARuGuFSaN1GGaOqmaN0MomlMcTSTnIJU3zY7UoPUMZ-H4XP0mgaJj3p2AkC78HxvXjWk87B0_NdKZxIt9M0cElEi1htVxqnUUw4LdbIrTcDfR3HQydxJJfHD5-dyHOCRKXpr5g40XiKSKeO7z-AusGO5KX0L5oyO_X8hERDKMOR4ejLFBWkiA0f7NPMHv66mM3DKJHIC_7n2omSxWF34vgxYYC0BOjEiRfQDAQoPd_v4tifB-4TtnQbhn6cIUnOfE4Ct0DjNiJEcjIVNsZO0MHjH9LMiaHXC7YuYhyNkFC8cCkPghA6ACvRkPtKz7C1vgX_2oreUw1b7WlGX1Z6qqJpZk-HCMru6bZlaT1TNmQDysGJ7Gm6bms9TVXgX0Pv24Cq26rR0xUA7Wl9Gyjqigo_dQXIaLZuAjg0AeCaYsg907LUnmprar9nKrqp9DQZ-gH_mgagKpaM_8q6DSVAoqfAP9AnW9ahJbvfB1wZu63rhmn2FBVcs56qaVhpa0bPVHVTB8KaAW1bsgy9s2yzp_Z1q489VTTAsftyz1A1bNsw-yb87sMAbEUxAbOvAmf6lirDIOU-_AQwVVdhXLppG9gOcKMHYSYMWjUV6K6pIhs0W1UM7JAG4wVvsWfqBgxat2VgpiED63QYqdoDnWT0e4qCTAPHEvoMfgt0CLpiKb2-pUFDiqxYAAKgPU0xkdOaBZWGblpGD8ZtQM9NQ4XZUBTgpqHh9FgW_KtY2EfdBrZD16FxHIuOY0EyigJTAKORLSjX5T6yRIZZViF87Cl94AKE7wY2YeswLl031Z6p2TZMhi4DpmHYMjQK0MhdDbqn91XglK5ZWAKTDAPu94GlugKgOD6YDaNv6DB6VQf-Apf7NnISOKFA17DHFtJUccKBfRqMXzNNmFDF1E2YP0WHbhk2MkQFeeuhcEL3QA5MXQNE01JxTlVDQ55YONe2RZc75mKcaDEoroLAg0WXwEIqpdOzepkuqd8O7m4u6Y_fpkkyj9_t7z8_P-_NnWQaTsgLeHh7oND254AEi3E3_u75_i5S3R_A_44eB0eTiTE0jjT_6TG8_zZUbu_fL06ewj_j-8_v9Wn0oZ_0Hy6-XM---Z92b2V19_T-_Zev_vXX62A6lx9-BM-nf0411z5_v2u7oRveyV9U9Wp8d3QdOfr95UJ_fx4cf-sPhk_RwJC_fHj_8706TK786Mr7kjyf_rFr9a_Pp-bd45V3477_M9nVjmbq6OOXz_7u1y8X_t34afBJCb4e2aOXH1_vfpyE6RWRv3rKeHbsDIzL6yPruX9xqfz12h3p5g8y_nSX3j8bNw_m7s90-sX8_PL1x-L555-PD7d3z344X4TnC_V8oj1-tX4-zT5NP3z96-78k_n94dvg5o_II3EwvP3jfWx9_hn6P-6fn04c7eKbEdyMvhyNBgNyNTy7Pvt-dHX3dXyf3g5Hg88DJ525g2_a1ZP2xXp0_7CBq4eHdGL2s5k5YBscMZsm_hdVcTiPVIi6kpeQGVV-JjMUrwGpMAqAVh0g1WsCoF0LiEtOAOzXAdL1nwNmAV_FYFALCBT1WkBUzwIgd-yAayKzDtDLijywBZwKuN-R95AmJKsAQ_XygRsLqv3ZaqTKm6921OnQUpBwOGYruDnJ9C21DKjNmG1hdkNXTcPmCouZCbaWmd5nionZA6b9mfJRAE3N1AtV1kx7MwXCVBPT7aaGtoEpbWaAuNKmWoKpXmavqPpjZozpOW4uDJSIOIn40JZMLPANeAp2lzoBaJjxx4cwYXVYmP1xMELtEINzESVnZBYfLcCZPMVIurTDwC07Qo9IwpwWESfb3HPJxEl9LP-UgkOEjoYsll6ybcYgjGbLDCeQAkcDYx5G8XYxx5ENLi-5C8FblTw3cyt4Id1LHORdO3b8cUw75wVjPwW5C7gzvXRdfOcBO4C7o5iuc8VdSYHSsqHfDqBH1KOEHlyAt_fC9TTDP_NDcPzUjArfRVXlYr2S1T8xHw3ln_mrQ8YZ8DSBC9gwVtHwHooYSFf6IbDyka2eK5I4LviT-xewnOJ96OM-7Tf8eE04cGbcKcs82lfDH4dpwKdVGCrnJ453f3NuKKuZcUodRBZpc0EQ-MFLRKC1WBPv58J1Bb6u5_i3BFxikTO8XOIV28WeizE5Ar1ZyxlevzFTOL7IDyiSWNl2seKeOPMwOPFpXJ2lj2oZUwm9MZuuIw-01gBU14ymYXNusRopr9oupp2TSVLLI6xcU9MsOYK4Ih_Y31umW8KoQadA5cbygMji6Nnfm43-gOnvfwHjBj7jSp6fwXo4JU4scnxZ9orfaiu7JtDMWY6FEi_dtjXHU0INC49DbCyAQtpJXIPLwu3iiJBEq-WJALMxVwQaIl8Kxb8WKRUUx3c_TngWU5iMUs16CzZerthXDRSEtJhD3TZhHbgucXEfY4WHUYLbXGhD3CqdpGzbUJBaKJfyiu1i0pnvjD2aMa7lTw6yMWtyEgXNL5RuWzATHdMdhYZIhkNszJPLMHiMaSCXcyQv2y5-CIeS6DZALVvKgJtzp0SowKWsTlpWbpmZhBV_TQKSRM0rqwT3Js0j0HmlfAp1v-xmbh0vcF_-lc2E0rfaS0q4ylbSii20k8s11cZYloDfvsirzGa-yrfVdrKDHbfhaBo25LwKUG9Y4sHyfI24uvPSLct3BeMIYjriDuA_Hyds37g--1UF_YYE4WPgTTziMjrFHCGvkrK67WIbbgGM6WGHWl7lIBszKCch8kYs3TZhCujNiob0aQaxaRpsSaCQQc0Lt8pq8op_-obHMbhbHwOqyAp7HYkj1GxqOgvExZg_TqQwkHjFP1Ew23DkyPH9paESeFIoX3edcoaUaAtbQFAhCTXbtVhHPp48yw-rxrWL9hXkxgptSMbEJ6-932L5lim12ZwkaT13eP3GCo2hF9RZVrRdjGCnv29IQoLGaKkEtyljSmREBrEqSaj7FSyJp3Tx-OtyVsTiDfcDipSrXH9asV3iyu_skjYargJ2Yx03GjtJQqJyyqhQvG1pkAAvu4D6zVzxhkxIGfQtkVKJVCliWtZuaQyA5xdInKRhGtOjDLVMKwNuzLIbL4bFxsmJ3GIV0rJmy-TLD2OyIk8rwGwuUTmNgihhsZSV_7IUEEFGDx8noySMZrEwE0LpprFBgbAQsUYPmFPLKrYuO-QFTVkh7w0JX8QuyCIr2DJLGUZkmNblwCtqNz_Wg6etY_DaimnXQvF28eYu8IkTT2vlg9dvzBGOL3JjWbSdmcJLb-atzhBSqDclvpyHNHCdkqSUKn5le_Ccnhe4Q-SHeK4gL9zQ5xep5vzHUikr3i75PPKhb7VySWs3lkeKXUjtsIJfzsRh92wa4kNPQWGLLi_c1JUQyQpHEbBUGjpbaCku8d5hrRWtqN38MKQT42nKZ3qlXjgTiRnYZfmbRZP_BFB6uYFdX8CfFIlCXATzNKE9OOzOvHj8FS904uNi9NoEfQ_t5PT05Pj24vMJv6EpolDmfA3S2QNVMvS_2ZVKWBiEbphJcfoQs5-H3c8eeaYdGQKDPD_Gcfm-M48F_YtXF3jPfYwa66lRqHNv-UpZNa0coJ7SyQuJEhjvvRON8aJTHa1l_YpOsQbxBQS80VpHDR__qifETu9jWp690FDDKfrWWj0VfP2sdjhY2YB7MZs7fm3LvHYFJxK8oQLi7U28Md44bp5yvM_CoBr4Mh7DOhwvGuabvwRQT4O-plZHgFXWI7MX0eqweW0DV-lrbLVcZbX16EMydmrHzirrkZePfoQBfRmwmsoSqoHShzCgQg6LZuD5eJK_dmZPfLIEqSf4MZmSiF97rqN0BToqA2lcOOwaXC0dAaKBV_TdpBoOYV09KnsVqGYMWNewaPgjOXWr3WtessUHbGrmQ4SpJ8VefKnVg02o7BGIWvbzFyUaZpC_pFIze6y2gQnZkzI14-fVDWuMqu_BU-jxOKVmtZXAmvQN3VR9Kxn6TsrbyZQfTnk7xVPfib_XzjevrUe_Szz0oCqoMOenFRFck2-jgEvzbRTw_YzZxtg3ZS8mx71p9l-WL31UIme1TWqDPwCyMQX2TMnG6PQVlY2xqe0YkgkmoBqNxxKmYXEkaZA5-m8kRbtVrUXy0a1Fi5nRypGuTZGtbv6OYJMCYCArCIEfcN7gabajtHwN6Jw4Pj49G_pvI_jqvcS3EMM3zdK5E7gZuY9V_n0-Dy25FyYx0KQP0Azx6bS38jAgs0UFofp-HexnESF9mgZjNP6gziiJMEPxMwxnXw67u4pi7amWbSuqphsaK-e31BWFX00H533owTRGVPyyZhHyT6BgGsqeZdqahm_x2exZgwMaI_Nr8_h7eWu-nl4aE_ZKK7u1SjEYp1iQClTEK_A3EOUni3fSzeDmpHMeRlEYSR_AIndOXuYQ-ElDiOBZwCsdhc8dik4H9k6ylQ6_nv9OUuUOf3_hnTSSRp2bNCDvpIsIZgB_vvqbkrghP95Jlt2BcMn3xh7iqp2_wWggRkn-_rcIAP-uy3_BRBE7mill771JbKI6eBOdBYOxNPEiIjmB5Liuh_NNb9JG0GdFtppoDFw3ljRbSkLJNF_V7ii6jlVZaCVBxAnMgHIgCuUYJwrwwKQgjTum2CDroETD0Q7GDpLWl9AkS8BhiQql9AdEeFCLaYqr0KUPpksR_nvYlfeMLp8xnsiohVBXQmgrIfSVEMZKCHMlhLUSInvkkeaJiqKrFkX37sPFp7uTziD5CRHAf4DQx_8dS0MvdoHVnTO8fHDsRWOfJB1-uIb59yB68pryzG4L-aJI49vF0nEIooe30JwxSIcg3LrcKNw7isqECDvJXH80h6_AuKjhI3Ii2I5hYvmMaXIJfbSOYouix1hED_1TTTIJ08DtqPpfsIhLbILaTnpY4FM_JJYKPGLiqhoUnlsMJroOQL4kkbMsLeIBR6J0nvzbiXSVOGqV4ngOlgu5dg-CGM4k_GtA7VDnNI1Qn0v3EdifDg-53kmmXJZPVSvKp75KPquEsY2YGqoopsprMdVrBFCxsHxIXhKCg-_sqAoWXAQJhFHeIxqmjlanC6n6Uw0BnapiSkGR89OlS0ENl7oeMQGk0M6_pshVCZReYZqPp-BNRd5YAj_EcTPrfEocdH6BlyMQMLDUZRHqF1UcGNtqEWolJpbRLCY1akormPDsNUtuD3f6qqjDULeAXuu_0ms76AhAIT46WhBBTatUoTuqScuFc3x55f83M1slZEaFkF05BJ09UFcfcAuigw-SwJR9SkFdRWVbmcuFqRflol_r_bAFbuDEqFrZ1xIWOAekYqDpbNLdV0CGKjbEiTx7yVSiLxTRXZ2Ootb2Zkexi-qLWTv9l3NWKzVmta0DlTRNQRlH-PNpIR0RP-nQjI808kMmFQXxkUXrIxfFB92TfMYw6SDdTiMCMQ84FjuG9lpfaNRFh5CMBI_JFNa-XJzX-yl4OIswpTMpOegWEWkWBnhzt0crHnHmoX1QTy5ezorQVwLrJPNnFuMtmv2qebEqVvNpSLjn2xnMSAKLLZFuMHYpzIQqLuSSgt9RtGqVzo2I9J98PS259l_vJOD-X_j6pctLk1cudJXOn6YwLf56oe8oivraImhKtUVQ9WqLoGu_LMLbAi-7QsrOHB9PoHp-g5BZfVHISsu9zm1oJ2PM4WwhY9SWgEWpsSWCZdK0OjlUC74svRaWWRK1qIEU5n3gLanlu2HC4OJfAtdK4PoVAncETkmchAGRqIEBJ9Z3ImkwSzHCr_VRjH5NJD7w_RD8XIh8h2E4i_HcCkwfNSBsSxEEVK7KACkFt3ZWGQaDzhEJKXomFPk2K3qwr2KmHU3-paveJjqKXCE7J7P5AiYskP4gZJ4FUffOC0zgewdjoTwcV2RLL0dTuqz_AzKgZnNYVcyAsh3ensT7SfMKJZlTVCpQGUSWsNQLyaIijl1w2Rtoa_0K78tYLzLjuvGVwv8l163kupS4vxqcXRx3BoHjg-nNsp-Y9QSXl3ngEMonU7TRcy9M46JhVnMBthtc8jsUi-cqLxqc5LvA-5ESFit1LsEogiHtgUUecc_5GBztdAYK1paxL4qsS3zfEi9VpzHpHKcRGM7EX0hTJwZVndWXQoFs77GDnp9ghznwPy7qUdQqnhfucd35iTeDXyx2pPvZGeOP8HyiN0n9ou7QCrqjzj-SO_x7QcBUy1QZefxb0l4zWGEMBjemkcECQMcs5IsHM-yrxJsEx8bQ1-b0m1JfilbFabxEAfyhu1BLRmMQUGJ0RJ5LeQrTXpfLmqUy0nVMtrA5awWL8_qODSychVQ3sg8_Sd4EMXBBeeA7A_5l-MxiGhVmI8KvGOXMpnkIbOAfyPSqhONn78mD6NunqZ-TGX09qKg7ShxUzIZsDCzl2jRwDqMU_Ov8xmq2GVewUuw0Ya4UtjtAV4zqTStMPEAYgeI7dKLvAYnjDm6c717S0-CeMwPpK0fsN47rpcD0S5SQDr2PAgxJQppmEefkQ5jgUWnpmn3GgefEgIkSIwG-aBxKjzCORKLJr8LO0HKPh5pwPgfrkFSLiRweHP3fTFQlk80KQR5GziM-3gFsoRmqKlm2S7KsFnyuyj1emh_icsxZo9dmGhW1cW1cwcxnjJw6wNSigWP3KNgJkFzeizTpq0JJ6tLMPV8aaKu9YALDSv6NdkcUq1JboZo8J06UtJpgrX6qjMapUpRmFVWWnDCOH0C73xA_dFzexJZrKrvyZEgAYQdEH-NpJX9NrWQM5Bo2cSabm6yvonl4NTVaCwuz5ayvyncMU_Bwznx6ibSa9_0S7_W3G-ICiTyDlU1Evz5Dj94NKh7UYwGLRxLpgUDogHABHkogY-oobflkqFUJhGMnijA0HkLYGpFqv8gqTke_cSXU24xW86Q2ztPWMhi_w1J_UK34iRY_TOjnfq4f7m4u8cwdu2F15oMzHedfAlp2pQ6BNSMpwseDVqGw6ELEUFehsDxkjtFfhcBidOGTRnI9BjsImJ30E_HFPubDovmoCxewy1-NYrjvIV7yJeFDUllLrfgiflOqLfcFHGMVCm4i5uBm06j4J67EUQlfvSqPqoIA_1CVSED4dlVLtmQSJo2e8QOfLSaU4eF-icgZu6mn_CNdYk-F73a1GCr_1FZBAvKvb7Uc6lHoLqTsLspSCuTGjrOPhhU6nn9HbD0Wq7Usrhow-2RYYcD5V8RaNkznSFhlVrt1ra4hBufEn4mqQ109CWEiaMCCqmV3W_HYsuOCnsUjy_cEdxP4B9LoJ06faQm-EIUfk5Xl5dVrvJEt0U92FT8myxuoJMraZddow2DiPXJ1xf7gJ5cp_rJESrzEJ3g3j35mqqj4xeu0P1ISJ4Nxon6gn_z67Pg-WWRpn1svcfBEd3Yvt-jB01zOMvUywcMt4m2TmnaOQcOu1QzNy7VtBq0ePaNMc6bHU3q-pCs9hKFPnIDr94buaYwNt9CrzySApo6jxTwR-lY8cpX7BfyWRO6tVbVCsFMX8RGELjlF-lcF8Iw9L-aR6Nbx_Gf2lkB23VluHATlcf0Yduhm7KCwWbaamfSNzlpmXvvOmOC4IVgUBstuCi_7bcnyCoTC158ztFVIpSerc0RDNVe1Fy1v7uZY9TjsNWi6Z_3q8nl9G8vPT6zTM9z1WQsrF5h7j51dpB09xsTziPgTocNGix6XJ0FrPQtrY9JJL49VVeQWHFq7Lf5B-9D3qVstymbDtI9DejOl9bzH3qPnf5zQG2aARq_JtRWXzPhn8H3ZXjVf2RGN9aVseW11yQZVb7Fkyg1lbD_YX5ogdsmH_vV752D_2kmmHyf0xhGIiPp7538Bz-K80g==
```

### Screenshots

![Image](https://github.com/user-attachments/assets/6f2a8a88-38b0-4d6c-a2e9-70fd6e290b86)

**Comment by QuickStick123** [comment]
What are you searching for?

**Comment by QuickStick123** [comment]
Radius jewels will probably get nothing (not implemented) so goes for flasks and charms as they probably won't have benefit stats that match your stat weights.

**Comment by CashKiller28** [comment]
@QuickStick123 I've tried to search for bow, quiver, ring, jewels... Nothing is working. Tried deleting and putting the POE Session ID again, but didn't solve the issue.

**Comment by QuickStick123** [comment]
I think this is caused by fullDPS the default option not having a default of the active skill. If you add it to the fulldps it should work.

**Comment by CashKiller28** [comment]
@QuickStick123 The issue was solved by marking the active skill in the full DPS calcules, thank you!

**Comment by QuickStick123** [comment]
I will keep this open because it didn't behave like that afaik in pob 1 and could lead to others being confused.

**Comment by QuickStick123** [comment]
I will keep this open because it didn't behave like that afaik in pob 1 and could lead to others being confused.

**Comment by redbeardaz** [comment]
Can you say more here? I've got full dps on skills and I'm still getting the same error as above. 

![Image](https://github.com/user-attachments/assets/ad90cbca-5d6a-462b-9a72-d0ecb71be616)

![Image](https://github.com/user-attachments/assets/6b0d4547-4cae-4673-955f-736bb505474d)
