### ISSUE TITLE
Crash since 0.4.0 upgrade and not able to recover.

### ISSUE THREAD

**Issue by kirmsi** [PathOfBuildingCommunity/PathOfBuilding-PoE2#699]
### Check version

- [x] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Screenshots of crash/graphical issue, version and options menu

Upgraded from an installed 0.2.0 to 0.3.0 (which was working) and today to 0.4.0, when starting 0.4.0 this happened:

![Image](https://github.com/user-attachments/assets/67572483-8c3a-4964-b404-7cecd6c71b8a)

Here I also tried to install the missing .dll by installing [Visual C++ Redistributable x86](https://aka.ms/vs/17/release/vc_redist.x86.exe) and rebooting my computer.

![Image](https://github.com/user-attachments/assets/346a5437-13ef-476e-93b5-32a342e3f5be)

I have also tried a fresh reinstallation of PoB-PoE2 with the setup from 0.4.0, but this won't help. Downgrading with a new installation of 0.3.0 doesn't seem to work neither. 0.2.0 Installation now is broken as well. :(

### What are your system specifications and configuration?

Operating System: Windows 11
Graphics: Nvidia GTX 1080 with latest drivers
CPU: intel i7-8700 

### How to reproduce the issue

Try to start or reinstall PoB-PoE2

### PoB for PoE2 build code

```shell

```

**Comment by osaulonery** [comment]
same

**Comment by kjaerhede** [comment]
Same issue for me as well. Windows 11. Still fails after installing visual c++ runtimes

**Comment by renamedthewild** [comment]
same

**Comment by techicode** [comment]
@osaulonery @renamedthewild  you guys also win 11?

**Comment by hurricanecoder** [comment]
Confirming the same issue - I’m also on Windows 11.

**Comment by kjaerhede** [comment]
I've fixed the issue locally. I've reverted these 2 changes and re-run the installer and it works again. 

![Image](https://github.com/user-attachments/assets/b1fc2149-6ec5-4014-b432-81559b9e6cd0)

**Comment by osaulonery** [comment]
> [@osaulonery](https://github.com/osaulonery) [@renamedthewild](https://github.com/renamedthewild) you guys also win 11?

yes

**Comment by Wires77** [comment]
If you all want to download this file https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/raw/refs/heads/dev/runtime/msvcr100.dll and put it in the same directory as your Path of Building Community (PoB2).exe file it should fix the missing DLL issue until I get a new installer made.

For the second issue (that should get fixed by @kjaerhede 's fix) can you let me know the locations of your .exe and your .lua files?  They should be your install location for the first one at least.  Viewing the console using Ctrl+` may give a clue as to where they are.

**Comment by kjaerhede** [comment]
My .exe file is in %AppData%/Path of Building Community (PoE2) and there are .lua files both in this folder as well as its subfolders

**Comment by Wires77** [comment]
@kjaerhede was this before making the change to revert that update script?  Sounds like things are in the right place, and I can't reproduce this on my Windows 11 machine with a fresh install from any installer.  Does your username contains Unicode characters?

**Comment by kjaerhede** [comment]
@Wires77 yes the files were also located there when I received above error. My username doesn't contain any Unicode characters. 

The values in UpdateCheck.lua have returned to "." for both variables, but now I am able to re-run the installer without re-introducing the bug.

Upon un-installing the program, the file lua-utf8.dll remains in the %AppData%/Path of Building Community (PoE2) folder, but again when re-installing I don't run into the issue, so I can no longer reproduce it either unfortunately

**Comment by poliroly** [comment]
![Image](https://github.com/user-attachments/assets/425996d5-257b-454a-9acb-a7128a38d279)

Still receiving this error as of the latest installer upload (0.4.1)

**Comment by PontusMagnusson** [comment]
Still broken even when doing a fresh install. (Deleting the old and reinstalling from downloader.)

Downloading the portable seems to work, however this required me to move the builds from my documents folder to the builds folder inside where the portable executable is located.

**Comment by viters** [comment]
@Wires77 Had the same problems previously, works now, thanks!

**Comment by kirmsi** [comment]
0.4.1 is now working for me aswell. Thanks for the fast replies and as usual good work!
